### ISSUE TITLE
Hooks issue with webpack (mjs)

### ISSUE THREAD

**Issue by gpoitch** [developit/preact-render-to-string#86]
I still encounter this issue with hooks: https://github.com/developit/preact-render-to-string/issues/72 specifically with webpack.

Seems to be a mjs issue, since using this fixes it: https://github.com/lukeed/webpack-modules

Does this same thing done in preact need to happen here too? https://github.com/developit/preact/pull/1425

**Comment by marvinhagemeister** [comment]
We switched back from shopping `mjs` files in Preact to plain `js` files. We still ship `mjs` here with `preact-render-to-string` which causes the mentioned issue.

**Comment by marvinhagemeister** [comment]
Good news: This is fixed with #89 . We'll cut a release in a few hours :tada:

**Comment by hesselbom** [comment]
@marvinhagemeister I'm still getting this issue. Not sure if it's with preact, preact-cli or preact-render-to-string.

To replicate:

**index.js**
```
import { useState } from 'preact/hooks'

export default () => {
  const [a, b] = useState('c')

  return <h1>Hello, World! {a}</h1>
}
```

**package.json**
```
{
  "scripts": {
    "build": "preact build"
  },
  "devDependencies": {
    "preact-cli": "^3.0.0-next.19",
    "preact-render-to-string": "^5.0.3"
  },
  "dependencies": {
    "preact": "^10.0.0-beta.1"
  }
}
```

When running `npm run build` with those two files I get:
```
TypeError: Cannot read property '__H' of undefined
method: null
at: ~/test-issue/src/index.js:67:19
```

An interesting thing to note is that if I don't have preact-render-to-string as a dependency it complains `Error: Cannot find module 'preact-render-to-string'`. A problem I didn't have before as it looks like it should be imported from preact-cli.

**Comment by marvinhagemeister** [comment]
@hesselbom Had a quick look into it and it seems that there are somehow 2 instances of preact at play. Could be an issue with the cli, I need to dig deeper.
